services:
  pong-game:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    command: npm run dev:full
    volumes:
      - ./node:/app
      - /app/node_modules
    stdin_open: true
    tty: true
